# Generated by Django 4.2.30 on 2026-05-16 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_usersubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='user',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='date',
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
