# Generated by Django 6.0.5 on 2026-05-20 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0005_remove_meeting_participant_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('utr_number', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.user')),
            ],
        ),
    ]
