# Generated by Django 6.0.5 on 2026-05-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0006_user_subscription_duration_paymentproof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_duration',
        ),
    ]
